server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
      

spring:
  application:
    name: app2
  profiles:
    active: dev
   
    
  autoconfigure:
    exclude:  com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 去除druid配置
      
  mvc:
    servlet:
      path: /
#    static-path-pattern: /**
   
    view:
      prefix: /templates/
      suffix: .ftl     
      
               
  freemarker:
    cache: false
    charset: UTF-8
    allow-request-override: false
    check-template-location: true
    content-type: text/html; charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .ftl
    template-loader-path:
    - classpath:/templates/
    request-context-attribute: request
    
  main:
    allow-circular-references: true    
    
mybatis:
  mapper-locations:
  - classpath:/mappers/*.xml  
      
logging:
  config: classpath:log4j2.xml
  level:
    root: debug
    javax.activation: info
    org.apache.catalina: INFO
    org.apache.commons.beanutils.converters: INFO
    org.apache.coyote.http11.Http11Processor: INFO
    org.apache.http: INFO
    org.apache.tomcat: INFO
    org.springframework: INFO
    com.chinamobile.cmss.bdpaas.resource.monitor: DEBUG
    org.apache.ibatis: DEBUG
    
#web socket port
socket-port: 9997

#远程SSO认证服务业务接口地址
ucan:
  sso:
    server:
      host: http://login.ucan.com #sso系统主机域名
      port: 80                    #sso系统端口号
      toLogin: ${ucan.sso.server.host}:${ucan.sso.server.port}/toLogin  #sso系统的登录页面地址,这里的域名要跟pass.ftl中的window.location.href配置中的域名一致
      login: ${ucan.sso.server.host}:${ucan.sso.server.port}/login   #登录验证与jwt token生成
      verify: ${ucan.sso.server.host}:${ucan.sso.server.port}/verify  #jwt token验证
      updateToken: ${ucan.sso.server.host}:${ucan.sso.server.port}/updateToken  #客户端token过期，通过发送refresh token到sso服务器进行校验来生成新的token
  redis:
    host: ucan.com
    port: 6379
  token-cookie:
    max-age: 86400  #token-cookie有效期  
    